import type { Section } from './types';

function escapeHtml(s: string): string {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function stamp(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}`;
}

/** 导出 Netscape Bookmark HTML（可被 Chrome/Edge 再导入） */
export function exportAsHtml(data: Section[]) {
  const lines: string[] = [
    '<!DOCTYPE NETSCAPE-Bookmark-file-1>',
    '<!-- Generated by PegNav -->',
    '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">',
    '<TITLE>Bookmarks</TITLE>',
    '<H1>Bookmarks</H1>',
    '<DL><p>',
    '    <DT><H3>PegNav</H3>',
    '    <DL><p>',
  ];

  for (const section of data) {
    lines.push(`        <DT><H3>${escapeHtml(section.cat)}</H3>`);
    lines.push('        <DL><p>');
    for (const item of section.items) {
      const href = item.u.startsWith('http') ? item.u : `https://${item.u}`;
      lines.push(
        `            <DT><A HREF="${escapeHtml(href)}">${escapeHtml(item.t)}</A>`,
      );
    }
    lines.push('        </DL><p>');
  }

  lines.push('    </DL><p>', '</DL><p>');
  const blob = new Blob([lines.join('\n')], { type: 'text/html;charset=utf-8' });
  downloadBlob(`pegnav_bookmarks_${stamp()}.html`, blob);
}

/** 导出 JSON 备份 */
export function exportAsJson(data: Section[]) {
  const payload = {
    exported_at: new Date().toISOString(),
    app: 'PegNav',
    categories: data.map((s) => ({
      name: s.cat,
      links: s.items.map((i) => ({ title: i.t, url: i.u })),
    })),
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], {
    type: 'application/json;charset=utf-8',
  });
  downloadBlob(`pegnav_backup_${stamp()}.json`, blob);
}
